#!/usr/bin/env bash
WALLPAPER_DIR="$HOME/Pictures/wallpapers"
CONF="$HOME/.config/hypr/hyprpaper.conf"

echo "# Autogenerated hyprpaper config" > "$CONF"
find "$WALLPAPER_DIR" -type f -name "*.jpg" -o -name "*.png" | while read -r img; do
    echo "preload = $img" >> "$CONF"
done

# Set random wallpaper from the preloaded list
RANDOM_WALL=$(find "$WALLPAPER_DIR" -type f | shuf -n 1)
echo "wallpaper = ,$RANDOM_WALL" >> "$CONF"

